services:
  web:
    image: mrbartusek/dokchat:latest
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
