services:
  web:
    image: mrbartusek/dokchat:latest
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: on-failure:10
  postgres:
    restart: on-failure:10
  redis:
    restart: on-failure:10
