# You can use this file to define resource usage estimates for Infracost to use when calculating
# the cost of usage-based resource, such as AWS S3 or Lambda.
# `infracost breakdown --usage-file infracost-usage.yml [other flags]`
# See https://infracost.io/usage-file/ for docs
version: 0.1
resource_type_default_usage:
  aws_s3_bucket:
    object_tags: 0 # Total object tags. Only for AWS provider V3.
    standard:
      storage_gb: 1 # Total storage in GB.
      monthly_tier_1_requests: 100 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      monthly_tier_2_requests: 10000 # Monthly GET, SELECT, and all other requests (Tier 2).
